services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: koerberDatabase
      POSTGRES_USER: koerber
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U koerber -d koerberDatabase" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: koerber_api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/koerberDatabase
      SPRING_DATASOURCE_USERNAME: koerber
      SPRING_DATASOURCE_PASSWORD: testpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGGING_LEVEL_ROOT: INFO
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin


volumes:
  postgres_data:
  loki_data:
