services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: koerberDatabase
      POSTGRES_USER: koerber
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: koerber_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/koerberDatabase
      SPRING_DATASOURCE_USERNAME: koerber
      SPRING_DATASOURCE_PASSWORD: testpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
